name 'fsm-opsworks'
maintainer 'Aaron Hipple'
maintainer_email 'aaron@footstepsmarketing.com'
license 'all_rights'
description 'Installs/Configures fsm-opsworks'
long_description 'Installs/Configures fsm-opsworks'
version '0.1.0'
depends 'mysql', '~> 7.0'
depends 'tar', '~> 0.7.0'